'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Rpa_OnOff
    
    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAllTaskEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllTaskEnable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAllTaskDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllTaskDisable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLoadAutoChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadAutoChecker As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEnableAutoChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnableAutoChecker As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDisableAutoChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisableAutoChecker As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSuspendScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuspendScheduler As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSuspendTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuspendTask As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDetails As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
End Class
